version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_1002Project
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: WmJDBCAdapter
  version: 10.3.0.0.34
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.siqa_1002.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_1002Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:test1002
  packages:
  - name: SIQA_1002Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
configurationVariables:
  jdbc.jdbcTestPool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/jdbcTestPool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.jdbcTestPool.maxConns: "10"
  jdbc.jdbcTestPool.userid: root
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionSettings.password
  : "{AES}B2Xqma4Ost5nVUiXctJydQ=="
  jdbc.jdbcTestPool.spyenabled: "false"
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionSettings.databaseName
  : SIQACloud
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionEnabled
  : "false"
  jdbc.jdbcTestPool.snoopenabled: "false"
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionSettings.trustStore
  : ""
  jdbc.jdbcTestPool.spyparms: SpyAttributes=(log=(file)logs/spy/jdbcTestPool.log;logTName=yes;timestamp=yes)
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionSettings.portNumber
  : "1433"
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionSettings.user
  : sa
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionManagerSettings.maximumPoolSize
  : "10"
  jdbc.jdbcTestPool.waitingThread: "0"
  jdbc.jdbcTestPool.minConns: "0"
  jdbc.jdbcTestPool.expireTime: "60000"
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionSettings.serverName
  : vmiboint01
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionManagerSettings.blockingTimeout
  : "1000"
  jdbc.jdbcTestPool.driverAlias: MySQL Database Java Connector Driver
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionSettings.dbType
  : MSSQL
  jdbc.jdbcTestPool.password: "{AES}er+I3U8nDVm8F4DBRST1+A=="
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  jdbc.jdbcTestPool.dbURL: jdbc:mysql://mysql.test.local:3306/webm
  jdbc.jdbcTestPool.poolThreshold: "0"
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionSettings.keyStore
  : ""
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionSettings.networkProtocol
  : tcp
  jdbc.jdbcTestPool.useSSL: "false"
  ? artConnection.SIQA_1002Project.project.siqa_1002.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1002.connectionManagerSettings.minimumPoolSize
  : "1"
